name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 16 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-label: 'no-issue-activity'
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          stale-pr-label: 'no-pr-activity'
          exempt-pr-labels: 'exrternal,work-in-progress,not-stale'
          days-before-pr-stale: 1
          days-before-issue-stale: 1
          days-before-issue-close: 1
          days-before-pr-close: 1
